# Generated by Django 5.0.6 on 2024-06-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosadicionales',
            name='ciudad',
            field=models.CharField(default='Bariloche', max_length=40),
        ),
    ]
